// <auto-generated />
using System;
using DAQ.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAQ.Migrations
{
    [DbContext(typeof(OeedbContext))]
    [Migration("20190316070407_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("DAQ.Database.ConfigDto", b =>
                {
                    b.Property<string>("Section");

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Section", "Key");

                    b.ToTable("ConfigDto");
                });

            modelBuilder.Entity("DAQ.Database.StatusDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Span");

                    b.Property<int>("StatusInfoId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("StatusInfoId");

                    b.HasIndex("Time");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("DAQ.Database.StatusInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlarmContent");

                    b.Property<int>("AlarmIndex");

                    b.Property<int>("StationId");

                    b.HasKey("Id");

                    b.ToTable("AlarmInfos");
                });

            modelBuilder.Entity("DAQ.Database.StatusDto", b =>
                {
                    b.HasOne("DAQ.Database.StatusInfoDto", "StatusInfo")
                        .WithMany()
                        .HasForeignKey("StatusInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
